### PR TITLE
Bugs with http server and Server documentation

### PR DESCRIPTION
**Pull request by tioui**
By using the http server functionality, I found some little bugs that I corrected. I also took the time to document de code so it may be more easy to use in the future.

### CODE REVIEW

**Comment by ramack** [comment]
Thanks a lot for your efforts! As you might have seen I merged the changesm but our nitpicking ET found some trouble with it, as 2 examples in the net and one in the storable cluster of the turotrial fail to compile (due to the rename of server).

What do you think? Shall we better undo the rename or adjust the examples?

**Comment by tioui** [comment]
I will test it and see what I can do. Just to be sure, is there a way to know what ET find as trouble?

**Comment by tioui** [comment]
I think that I resolve the problem. I create a new pull request at https://github.com/LibertyEiffel/Liberty/pull/142 .

**Comment by ramack** [comment]
thanks. Also merged :grinning: for ET: you can simply check https://et.liberty-eiffel.org in this case the the +3 in fails in [the history](https://et.liberty-eiffel.org/?history=3) would show the problem, while the other +'s seem not fully reproducible.

The challenge here often is, that most human programmers are not able to see all side effects a change would have - and exactly that's why I once setup the automated testing which includes all the different stages that could show a regression. And I'd be so happy to see a fully passing test suite eventually, while in the ideal world we would even create a test case for each new or changed functionality - but let's first restart the activities and have some fun, then we can put some hard tasks on us later :grin:

**Pull request merged**
